name: equiny
description: "Equiny Mobile App"
publish_to: "none"

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  reactive_forms: ^17.0.1
  go_router: ^16.1.0
  dio: ^5.9.0
  shadcn_flutter: ^0.0.36
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
