name: equiny
description: "Equiny Mobile App"
publish_to: "none"

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  signals: ^6.0.2
  signals_flutter: ^6.0.2
  reactive_forms: ^17.0.1
  go_router: ^16.1.0
  dio: ^5.9.0
  shadcn_flutter: ^0.0.36
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  file_picker: ^10.3.2
  supabase_flutter: ^2.12.0
  web_socket_channel: ^3.0.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  ulid: ^2.0.1
  flutter_animate: ^4.5.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lotties/
